load("@rules_python//python:defs.bzl", "py_library")


package(default_visibility=["//visibility:public"])


py_library(
    name = "chunk",
    srcs = ["chunk.py"],
    deps = [
        "//cyber_record/cyber/proto:record_py_proto",
    ],
)
